runtime: nodejs12
instance_class: F1
env_variables:
  BUCKET_NAME: "simpl-rent-doc"
handlers:
  - url: /favicon\.ico
    static_files: favicon.ico
    upload: favicon\.ico

  - url: /
    static_files: www/index.html
    upload: www/index.html

  - url: /(.*)
    static_files: www/\1
    upload: www/(.*)
